name: Renovate
on:
  schedule:
    - cron: "0 1 * * *" # every night at 1 o'clock (UTC)
  workflow_dispatch: # can be manually dispatched under GitHub's "Actions" tab
    inputs:
      dryRun:
        description: 'Dry run'
        type: 'boolean'

      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
          - info
          - debug

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-24.04
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_KEY }}

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: '3.14'

      - name: Local Conan versiontracker
        run: |
          python -m pip install -r resources/conan/requirements.txt
          resources/conan/updater.py --renovate=tmp/renovate/ -v

      - name: Serve Files
        uses: Eun/http-server-action@dadebd209d4a902eeefceb524c24c38b364c46a7 # v1
        with:
          directory: ${{ github.workspace }}/tmp/renovate/
          port: 8080
          allowed-methods: |
            ["GET", "HEAD"]
          content-types: |
            {
              "json": "application/json"
            }

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@c314dda4a9a93b08239ec978f2043b9a433b9ac4 # v46.3.0
        with:
          docker-cmd-file: .github/renovate-entrypoint.sh
          docker-user: root
          docker-volumes: |
             /tmp:/tmp ;
             ${{ github.workspace }}/resources/conan:/conan
          docker-network: host
          token: "${{ steps.get_token.outputs.token }}"
          configurationFile: .github/renovate-config.json5
          env-regex: "^(?:RENOVATE_\\w+|LOG_LEVEL)$"
        env:
          LOG_LEVEL: ${{ inputs.logLevel }}
          RENOVATE_DRY_RUN: ${{ inputs.dryRun == true && 'full' || '' }}
